spring.application.name=ai-resume-reviewer

spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-3.5-flash

spring.datasource.url=jdbc:mysql://localhost:3306/ai_resume_reviewer
spring.datasource.username=root
spring.datasource.password=Pavan@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




